import turtle

window=turtle.Screen()
window.bgcolor("white")

objTriangle = turtle.Turtle()
objTriangle.shape("classic")
objTriangle.color("blue")
#objTriangle.speed("slowest")
objTriangle.fillcolor("green")

objTriangle.begin_fill()
objTriangle.right(120)
objTriangle.forward(200)
objTriangle.left(120)
objTriangle.forward(200)
objTriangle.left(120)
objTriangle.forward(200)
objTriangle.end_fill()

objTriangle.fillcolor("white")
objTriangle.begin_fill()
objTriangle.left(120)
objTriangle.forward(100)
objTriangle.left(120)
objTriangle.forward(100)
objTriangle.right(120)
objTriangle.forward(100)
objTriangle.right(120)
objTriangle.forward(100)
objTriangle.end_fill()

objTriangle.begin_fill()
objTriangle.left(120)
objTriangle.forward(50)
objTriangle.left(120)
objTriangle.forward(50)
objTriangle.right(120)
objTriangle.forward(50)
objTriangle.right(120)
objTriangle.forward(50)
objTriangle.end_fill()

objTriangle.begin_fill()
objTriangle.left(120)
objTriangle.forward(25)
objTriangle.left(120)
objTriangle.forward(25)
objTriangle.right(120)
objTriangle.forward(25)
objTriangle.right(120)
objTriangle.forward(25)
objTriangle.end_fill()

objTriangle.begin_fill()
objTriangle.right(60)
objTriangle.forward(50)
objTriangle.right(120)
objTriangle.forward(25)
objTriangle.left(120)
objTriangle.forward(25)
objTriangle.left(120)
objTriangle.forward(25)
objTriangle.end_fill()


objTriangle.begin_fill()
objTriangle.right(120)
objTriangle.forward(75)
objTriangle.right(120)
objTriangle.forward(50)
objTriangle.left(120)
objTriangle.forward(50)
objTriangle.left(120)
objTriangle.forward(50)
objTriangle.end_fill()

objTriangle.begin_fill()
objTriangle.left(120)
objTriangle.forward(25)
objTriangle.left(120)
objTriangle.forward(25)
objTriangle.right(120)
objTriangle.forward(25)
objTriangle.right(120)
objTriangle.forward(25)
objTriangle.end_fill()


window.exitonclick()
